### ISSUE TITLE
[Bug] tps查询无法使用

### ISSUE THREAD

**Issue by Haocen2004** [limbang/mirai-console-minecraft-plugin#2]
config片段
`  s2:   
    address: 'main.lxy-unnamed.top'  
    port: 25562  
    loginInfo:   
      authServerUrl: 'https://authserver.mojang.com/authenticate'  
      sessionServerUrl: 'https://sessionserver.mojang.com'  
      username: xxx  
      password: xxx`
已经检查过账号密码是正确的
已经检查过服务器可以正常连接

日志：
`2021-07-30 21:56:14 E/top.limbang.mirai-console-minecraft-plugin: Exception in coroutine Plugin top.limbang.mirai-console-minecraft-plugin of top.limbang.mirai-console-minecraft-plugin
top.limbang.doctor.client.session.AuthenticationException: ??????...: The server has not found anything matching the request URI
        at top.limbang.doctor.client.session.YggdrasilMinecraftSessionService.loginYggdrasilWithPassword(YggdrasilMinecraftSessionService.kt:83)
        at top.limbang.doctor.client.MinecraftClientBuilder.build(MinecraftClientBuilder.kt:74)
        at top.limbang.mirai.minecraft.service.ServerService.getTPS(ServerService.kt:96)
        at top.limbang.mirai.minecraft.MiraiConsoleMinecraftPlugin$onEnable$1$4.invokeSuspend(MiraiConsoleMinecraftPlugin.kt:46)
        at top.limbang.mirai.minecraft.MiraiConsoleMinecraftPlugin$onEnable$1$4.invoke(MiraiConsoleMinecraftPlugin.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invokeSuspend(messageSubscribersInternal.kt:58)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:226)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:432)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:160)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
`

**Comment by limbang** [comment]
> config片段
> `  s2:   
>     address: 'main.lxy-unnamed.top'  
>     port: 25562  
>     loginInfo:   
>       authServerUrl: 'https://authserver.mojang.com/authenticate'  
>       sessionServerUrl: 'https://sessionserver.mojang.com'  
>       username: xxx  
>       password: xxx`
> 已经检查过账号密码是正确的
> 已经检查过服务器可以正常连接
> 
> 日志：
> `2021-07-30 21:56:14 E/top.limbang.mirai-console-minecraft-plugin: Exception in coroutine Plugin top.limbang.mirai-console-minecraft-plugin of top.limbang.mirai-console-minecraft-plugin
> top.limbang.doctor.client.session.AuthenticationException: ??????...: The server has not found anything matching the request URI
>         at top.limbang.doctor.client.session.YggdrasilMinecraftSessionService.loginYggdrasilWithPassword(YggdrasilMinecraftSessionService.kt:83)
>         at top.limbang.doctor.client.MinecraftClientBuilder.build(MinecraftClientBuilder.kt:74)
>         at top.limbang.mirai.minecraft.service.ServerService.getTPS(ServerService.kt:96)
>         at top.limbang.mirai.minecraft.MiraiConsoleMinecraftPlugin$onEnable$1$4.invokeSuspend(MiraiConsoleMinecraftPlugin.kt:46)
>         at top.limbang.mirai.minecraft.MiraiConsoleMinecraftPlugin$onEnable$1$4.invoke(MiraiConsoleMinecraftPlugin.kt)
>         at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invokeSuspend(messageSubscribersInternal.kt:58)
>         at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invoke(messageSubscribersInternal.kt)
>         at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWithImpl$2.invoke(messageSubscribersInternal.kt)
>         at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
>         at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
>         at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
>         at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:226)
>         at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
>         at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
>         at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:432)
>         at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
>         at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
>         at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
>         at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
>         at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
>         at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
>         at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
>         at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
>         at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:160)
>         at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
>         at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:126)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> `

正版的地址我好像写多了  https://authserver.mojang.com

**Comment by Haocen2004** [comment]
```2021-07-31 00:02:19 E/top.limbang.mirai-console-minecraft-plugin: Exception in c
oroutine Plugin top.limbang.mirai-console-minecraft-plugin of top.limbang.mirai-
console-minecraft-plugin
kotlinx.serialization.MissingFieldException: Field 'availableProfiles' is requir
ed, but it was missing
        at top.limbang.doctor.client.yggdrasil.AuthenticateResponse.<init>(Authe
nticateResponse.kt:9)
        at top.limbang.doctor.client.yggdrasil.AuthenticateResponse$$serializer.
deserialize(AuthenticateResponse.kt:9)
        at top.limbang.doctor.client.yggdrasil.AuthenticateResponse$$serializer.
deserialize(AuthenticateResponse.kt:9)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableV
aluePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerial
izableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
        at top.limbang.doctor.client.session.YggdrasilMinecraftSessionService.lo
ginYggdrasilWithPassword(YggdrasilMinecraftSessionService.kt:130)
        at top.limbang.doctor.client.MinecraftClientBuilder.build(MinecraftClien
tBuilder.kt:74)
        at top.limbang.mirai.minecraft.service.ServerService.getTPS(ServerServic
e.kt:96)
        at top.limbang.mirai.minecraft.MiraiConsoleMinecraftPlugin$onEnable$1$4.
invokeSuspend(MiraiConsoleMinecraftPlugin.kt:46)
        at top.limbang.mirai.minecraft.MiraiConsoleMinecraftPlugin$onEnable$1$4.
invoke(MiraiConsoleMinecraftPlugin.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWit
hImpl$2.invokeSuspend(messageSubscribersInternal.kt:58)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWit
hImpl$2.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$startsWit
hImpl$2.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1
.invokeSuspend(messageSubscribersInternal.kt:27)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1
.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1
.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscr
ibeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt
$1$1.invokeSuspend(subscribeMessages.kt:226)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscr
ibeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt
$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscr
ibeGroupMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt
$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(Ev
entChannel.kt:432)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChan
nel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChan
nel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(Intern
alEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEvent
Listeners.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEvent
Listeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrRetur
n(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders
.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners
.kt:50)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(Inter
nalEventListeners.kt:160)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$proces
s(InternalEventListeners.kt:1)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemove
IfRequired$2$1.invokeSuspend(InternalEventListeners.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:665)```

改完报这个错 账号密码确认没错 试了2个正版号都一样

**Comment by Haocen2004** [comment]
讲道理应该把正版地址作为默认值的（

**Comment by limbang** [comment]
你服务器支持正版登陆么？  我等下测试下  是你上面那个地址么

**Comment by Haocen2004** [comment]
是 1.16.5 forge 整合包 atm6sky

**Comment by limbang** [comment]
> 是 1.16.5 forge 整合包 atm6sky

协议库正版登陆有点问题，等待修复吧

**Comment by limbang** [comment]
> 是 1.16.5 forge 整合包 atm6sky

16:55:50 [nioEventLoopGroup-4-1] WARN  t.l.d.p.f.c.Forge1PacketHandler(Forge2PacketHandler.kt:87) - 未找到协议包ChannelAndId(channel=astralsorcery:net_channel, id=0) 对应的解码实现.
16:55:50 [nioEventLoopGroup-4-1] WARN  t.l.d.p.f.c.Forge1PacketHandler(Forge2PacketHandler.kt:87) - 未找到协议包ChannelAndId(channel=astralsorcery:net_channel, id=1) 对应的解码实现.
16:55:50 [nioEventLoopGroup-4-1] WARN  t.l.d.p.f.c.Forge1PacketHandler(Forge2PacketHandler.kt:87) - 未找到协议包ChannelAndId(channel=astralsorcery:net_channel, id=2) 对应的解码实现.
16:55:50 [nioEventLoopGroup-4-1] WARN  t.l.d.p.f.c.Forge1PacketHandler(Forge2PacketHandler.kt:87) - 未找到协议包ChannelAndId(channel=astralsorcery:net_channel, id=3) 对应的解码实现.
16:55:50 [nioEventLoopGroup-4-1] WARN  t.l.d.p.f.c.Forge1PacketHandler(Forge2PacketHandler.kt:87) - 未找到协议包ChannelAndId(channel=silentgear:network, id=1) 对应的解码实现.
16:55:50 [nioEventLoopGroup-4-1] WARN  t.l.d.p.f.c.Forge1PacketHandler(Forge2PacketHandler.kt:87) - 未找到协议包ChannelAndId(channel=silentgear:network, id=2) 对应的解码实现.
16:55:50 [nioEventLoopGroup-4-1] WARN  t.l.d.p.f.c.Forge1PacketHandler(Forge2PacketHandler.kt:87) - 未找到协议包ChannelAndId(channel=silentgear:network, id=6) 对应的解码实现.
16:55:56 [nioEventLoopGroup-4-1] WARN  t.l.d.p.f.c.Forge1PacketHandler(Forge2PacketHandler.kt:87) - 未找到协议包ChannelAndId(channel=exnihilosequentia:handshake, id=1) 对应的解码实现

而且协议库也没实现。高版本好多mod都要验证

**Comment by Doctor-Yin** [comment]
> 是 1.16.5 forge 整合包 atm6sky

协议库已经支持,tps功能暂未完美兼容

**Comment by limbang** [comment]
1.1.8已经支持高版本tps 但是挺慢的
